PRÁCTICAS PYHTON CLASE 6 - NUMPY

In [48]:
import pandas as pd
import numpy as np


lista1 = [1,2,3,4,5]
indices = ['1ro','2do','3ro','4to','5to']

serie1 = pd.Series(lista1, index = indices)

lista2 = [5,4,3,2,1]

serie2 = pd.Series(lista2)

dataFrame1 = pd.DataFrame({'PrimerSerie':serie1,'SegundaSerie':serie2})

dataFrame1.fillna(0, inplace = True)

#Creo un array de 5 números aleatorios
aray = np.random.randint(10,size=5)

#Creo otro array con 4 componentes
aray1 = np.array([1,2,3,5,6], dtype=int)

#concateno los arrays. El primer array que ponga es el primero en concatenarse
aray_concatenado = np.concatenate([aray,aray1])

#Lo divido en 2

aray_dividido = aray_concatenado.reshape((2,5))

#Apilo 2 arrays de igual dimensiones de forma vertical

aray_temporal = np.array([[1,2,3,4,5],[6,7,8,9,10]])

aray_apilado_vertical = np.vstack([aray_temporal, aray_dividido])
print(f'Array dividido solo:',aray_dividido)
print(f'Nuevo array apilado vertical',aray_apilado_vertical)

#Apilo los arrays horizontal. En éste caso queda un array de 2 dimensiones y se agregan los elementos al final de cada array

aray_apilado_horizontal = np.hstack([aray_temporal, aray_dividido])
print(f'Array dividido solo:',aray_dividido)
print(f'Nuevo array apilado horizontal',aray_apilado_horizontal)

Array dividido solo: [[3 0 7 4 0]
 [1 2 3 5 6]]
Nuevo array apilado vertical [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 3  0  7  4  0]
 [ 1  2  3  5  6]]
Array dividido solo: [[3 0 7 4 0]
 [1 2 3 5 6]]
Nuevo array apilado horizontal [[ 1  2  3  4  5  3  0  7  4  0]
 [ 6  7  8  9 10  1  2  3  5  6]]
